// AUTO-GENERATED by `nanoka generate`. DO NOT EDIT BY HAND.
// To regenerate: `npx nanoka generate`
import { sql } from 'drizzle-orm'
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core'

export const users = sqliteTable('users', {
  id: text('id').primaryKey().notNull(),
  username: text('username').notNull().unique(),
  password: text('password').notNull(),
  role: text('role').notNull().default("user"),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull().default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`),
})

export const messages = sqliteTable('messages', {
  id: text('id').primaryKey().notNull(),
  room: text('room').notNull().default("general"),
  userId: text('userId').notNull(),
  username: text('username').notNull(),
  body: text('body').notNull(),
  deleted: integer('deleted', { mode: 'boolean' }).notNull().default(false),
  deletedBy: text('deletedBy'),
  deletedAt: integer('deletedAt', { mode: 'timestamp_ms' }),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull().default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`),
})

export const auth_blacklist = sqliteTable('auth_blacklist', {
  id: text('id').primaryKey().notNull(),
  subject: text('subject').notNull(),
  expiresAt: integer('expiresAt').notNull(),
})

export const rate_limits = sqliteTable('rate_limits', {
  id: text('id').primaryKey().notNull(),
  hits: integer('hits').notNull().default(0),
  windowStart: integer('windowStart').notNull().default(0),
})

export const upload_usage = sqliteTable('upload_usage', {
  id: text('id').primaryKey().notNull(),
  bytes: integer('bytes').notNull().default(0),
  count: integer('count').notNull().default(0),
})

export const room_purges = sqliteTable('room_purges', {
  id: text('id').primaryKey().notNull(),
  room: text('room').notNull(),
  purgedBy: text('purgedBy').notNull(),
  purgedByUsername: text('purgedByUsername').notNull(),
  removedMessages: integer('removedMessages').notNull().default(0),
  removedMedia: integer('removedMedia').notNull().default(0),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull().default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`),
})
